# Generated by Django 4.1.3 on 2022-11-13 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('w_app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='city',
            old_name='nsme',
            new_name='name',
        ),
    ]
